name: Generate Profile Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: saymon-felipe
          base: repositories
          plugin_repositories: yes
          config_theme: transparent

      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-langs.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: saymon-felipe
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          config_theme: transparent
